### ISSUE TITLE
problem_description["problem"] -> results.problem

### ISSUE THREAD

**Issue by stklik** [altaris/noisy-moo#2]
https://github.com/altaris/noisy-moo/blob/9f329b824ffff270959542a2cba0ddb027794571/nmoo/benchmark.py#L243

otherwise the history will be empty (i.e. nothing written)

**Comment by altaris** [comment]
Sorry I don't understand what you mean...

**Comment by stklik** [comment]
The current `minimize` injects a deepcopy of `problem_description["problem"]`, but afterwards the `dump_all_histories`  is executed on the original `problem_description["problem"]` (which did not get filled with the execution trace).

During execution, the histories are actually written into the copied problem. It can be accessed via `results.problem` and should fix the history dumping.

**Comment by altaris** [comment]
Embarrassing 😐
